-- Migration 009: Add client_id for idempotency on manual finance creates
-- Purpose: Prevent duplicate transactions from double-submit in iOS app
--
-- iOS app sends client_id (UUID) with each manual transaction.
-- This constraint ensures the same client_id is only inserted once.
-- SMS imports don't set client_id (null), so they're unaffected.

BEGIN;

-- Add client_id column to finance.transactions
ALTER TABLE finance.transactions
ADD COLUMN IF NOT EXISTS client_id VARCHAR(36);

-- Add partial unique index on client_id where not null
-- This allows multiple NULL values (for SMS imports) but prevents duplicates for manual entries
CREATE UNIQUE INDEX IF NOT EXISTS idx_transactions_client_id
ON finance.transactions (client_id)
WHERE client_id IS NOT NULL;

-- Comment for documentation
COMMENT ON COLUMN finance.transactions.client_id IS
'UUID generated by iOS app for idempotency. NULL for SMS imports. Unique when not null.';

COMMIT;
